In [5]:
#Importing the libraries
#Pandas is the Python library which have all functions related to the DataSet
import pandas as pd

#import numpy as np
#import matplotlib.pyplot as pt

In [6]:
#read_csv() is a function which will retrieves data and assign to the DataSet variable 
dataset=pd.read_csv("Salary_Data.csv")

In [41]:
# It will print the retrived data from the "Salary_Data.csv" stored in the DataSet
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
#Storing the Data in the column of YearsExperience in the independent variable. Indepentdent variable is the input
independent=dataset[["YearsExperience"]]

In [ ]:
#Print the data in the column of YearsExperience stored in the independent variable
independent

In [8]:
#Storing the Data in the column of "Salary" in the dependent variable. dependent variable is the output
dependent=dataset[["Salary"]]
#Print the data in the column of Salary stored in the dependent variable
dependent

Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [13]:
#Scikit-learn is probably the most useful library for machine learning in Python.
# train_test_split function is part of the sklearn. model_selection module, which contains utilities for splitting data
from sklearn.model_selection import train_test_split
#Passing the below 4 arguments into train_test_split. 30 % of the Test set size 
train_test_split(independent, dependent, test_size=0.30,random_state=0)

[    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0
 17              5.3,       Salary
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,       Salary
 2    

In [9]:
#Value of the train_test_split is assigned to the X, Y of train and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [10]:
#importing LinearRegression function from sklearn library
from sklearn.linear_model import LinearRegression
#assigning the LinearRegression function to the regressor variable
# Create a new linear regression model
regressor=LinearRegression()
# Fit the model to the data
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
#coef_ gives you an array of weights estimated by linear regression.
weight=regressor.coef_
#print the arro\ay of weights
weight

array([[9360.26128619]])

In [12]:
#A Linear Regression Bias is a coefficient of the linear regression 
#function that is a constant term that corresponds to the point that intercepts from the x-origin.
bais=regressor.intercept_
bais

array([26777.3913412])

In [13]:
#assigning the predicted value from the x_test set to y-predict
y_predict=regressor.predict(X_test)

In [14]:
#print arrar of Predicted values
y_predict

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [19]:
#The sklearn. metrics provides a variety of functions for measuring the performance of machine learning models. 
#importing R2 it will represents the fitment of the model.The value of R2 lies between 0 to 1
#if the value is close to 0 the model is unfit and if the value is close to 1 the model is fit
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,y_predict)
r_score

0.9740993407213511

In [27]:
# save the model to disk
import pickle
filename="finalized_model_linear.sav"

In [34]:
# save information to that file in write mode in binary format
pickle.dump(regressor,open(filename,'wb'))

In [40]:
# Loading file to compare the results in the right mode in binary format
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
#the function predict() extract predicted values
result=loaded_model.predict([[13]])
result

array([[148460.78806172]])